// auto-generated by node scripts/ayush-news.mjs — do not hand-edit.
// 10 notices · 2026-09-17.
/* eslint-disable */
export const AYUSH_NEWS = [
  {
    "title": "Ministry of Ayush Signs MoU with Digital India BHASHINI Division to Strengthen Multilingual Ayush Digital Services - PIB",
    "url": "https://www.pib.gov.in",
    "source": "PIB",
    "at": "Sun, 13 Sep 2026 20:25:43 GMT",
    "src": "google",
    "id": "news-google-xr90am"
  },
  {
    "title": "Ayurveda charts global growth path with focus on evidence, quality and innovation - DD India",
    "url": "https://ddindia.co.in",
    "source": "DD India",
    "at": "Mon, 14 Sep 2026 15:17:00 GMT",
    "src": "google",
    "id": "news-google-jxn2no"
  },
  {
    "title": "Prataprao Jadhav highlights evidence, research and innovation in Ayurveda - Medical Dialogues",
    "url": "https://medicaldialogues.in",
    "source": "Medical Dialogues",
    "at": "Thu, 17 Sep 2026 09:00:16 GMT",
    "src": "google",
    "id": "news-google-j4t9l1"
  },
  {
    "title": "Union Minister Prataprao Jadhav highlights Ayurveda’s growth through research and innovation - The News Mill",
    "url": "https://thenewsmill.com",
    "source": "The News Mill",
    "at": "Wed, 16 Sep 2026 00:52:11 GMT",
    "src": "google",
    "id": "news-google-1nghlv0"
  },
  {
    "title": "‘Ghost Faculty’: NCISM bars 142 ‘on-paper teachers’ across 10 Ayurveda colleges - Careers360",
    "url": "https://news.careers360.com",
    "source": "Careers360",
    "at": "Tue, 15 Sep 2026 16:02:19 GMT",
    "src": "google",
    "id": "news-google-1v3x3ne"
  },
  {
    "title": "Ayurveda’s Growing Role in Global Health - Voice of Healthcare",
    "url": "https://vohnetwork.com",
    "source": "Voice of Healthcare",
    "at": "Tue, 15 Sep 2026 09:50:00 GMT",
    "src": "google",
    "id": "news-google-gioznh"
  },
  {
    "title": "BRICS countries move towards formal cooperation on traditional medicine: Ayush Ministry - The Statesman",
    "url": "https://www.thestatesman.com",
    "source": "The Statesman",
    "at": "Sun, 13 Sep 2026 13:14:00 GMT",
    "src": "google",
    "id": "news-google-ygwx5q"
  },
  {
    "title": "Jamnagar workshop highlights science-driven future for Ayurveda research - EdexLive",
    "url": "https://www.edexlive.com",
    "source": "EdexLive",
    "at": "Sun, 13 Sep 2026 06:15:00 GMT",
    "src": "google",
    "id": "news-google-1qo2om3"
  },
  {
    "title": "AACCC AYUSH Allotment List 2026 Today: Time, Link to Check - ummid.com",
    "url": "https://ummid.com",
    "source": "ummid.com",
    "at": "Tue, 15 Sep 2026 19:00:00 GMT",
    "src": "google",
    "id": "news-google-1voe1wn"
  },
  {
    "title": "Ghost Faculty Row: NCISM bars 457 teachers from Ayurveda colleges - Careers360",
    "url": "https://news.careers360.com",
    "source": "Careers360",
    "at": "Wed, 16 Sep 2026 16:42:10 GMT",
    "src": "google",
    "id": "news-google-15ad9e"
  }
];
export const AYUSH_NEWS_AT = "2026-09-17";
