// Live news feed: fetch Ayush + ministry news via RSS, write feed.js.
// Usage: node scripts/ayush-news.mjs [--max=12]
// Total failure → keep previous file.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "app", "src", "ayush", "news.js");
const args = Object.fromEntries(process.argv.slice(2).map((a) => {
  const m = a.replace(/^--/, "").split("=");
  return [m[0], m[1] ?? true];
}));
const MAX = Math.min(20, Math.max(3, Number(args.max) || 10));
const UA = { "User-Agent": "avsar-sih26044-news/1.0" };

async function get(url, ms = 15000) {
  const res = await fetch(url, { headers: UA, signal: AbortSignal.timeout(ms) });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.text();
}

const clean = (s = "") => String(s).replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
const hash = (s = "") => {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
  return (h >>> 0).toString(36);
};

function decodeEntities(s = "") {
  return String(s).replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'");
}

export function parseNewsRss(xml = "") {
  const items = [];
  for (const m of String(xml).matchAll(/<item>([\s\S]*?)<\/item>/g)) {
    const body = m[1];
    const title = decodeEntities((body.match(/<title>([\s\S]*?)<\/title>/) || [])[1] || "").trim();
    const link = (((body.match(/<source[^>]*url="([^"]+)"/) || [])[1] || (body.match(/<link>([\s\S]*?)<\/link>/) || [])[1] || "")).trim();
    const source = decodeEntities((body.match(/<source[^>]*>([\s\S]*?)<\/source>/) || [])[1] || "").trim();
    const pub = ((body.match(/<pubDate>([\s\S]*?)<\/pubDate>/) || [])[1] || "").trim();
    if (!title || title.startsWith('"ayush ministry')) continue;
    if (!/ayush|ayurveda|yoga|unani|siddha|homeopathy|panchakarma|naturopathy|ministry/i.test(title)) continue;
    items.push({ title: title.slice(0, 140), url: link, source: source.slice(0, 40) || "news", at: pub });
    if (items.length >= MAX) break;
  }
  return items;
}

const SOURCES = [
  { name: "pib", url: "https://www.pib.gov.in/rss/Releases.aspx?relid=15049" },
  { name: "ayushgov", url: "https://ayush.gov.in/rss.php" },
  { name: "ccras", url: "https://ccras.nic.in/feed/" },
  { name: "ncism", url: "https://ncismindia.org/feed/" },
  { name: "google", url: "https://news.google.com/rss/search?q=ayush%20ayurveda%20ministry%20when:7d&hl=en-IN&gl=IN&ceid=IN:en" },
];

async function fetchSource(src) {
  try {
    const xml = await get(src.url, 12000);
    const items = parseNewsRss(xml);
    return items.map((n) => ({ ...n, src: src.name }));
  } catch (e) {
    console.error(`${src.name}: FAILED (${e.message})`);
    return [];
  }
}

async function main() {
  const results = await Promise.all(SOURCES.map((s) => fetchSource(s)));
  const all = results.flat();
  const seen = new Set();
  const unique = [];
  for (const n of all) {
    const k = `${n.title}|${n.url}`;
    if (seen.has(k)) continue;
    seen.add(k);
    unique.push(n);
  }
  const news = unique.slice(0, MAX).map((n, i) => ({ ...n, id: `news-${n.src}-${hash(n.title + i)}` }));

  if (!news.length) {
    console.log("news: all sources failed, keeping previous file.");
    if (existsSync(OUT)) process.exit(0);
    process.exit(1);
  }

  const out =
    `// auto-generated by node scripts/ayush-news.mjs — do not hand-edit.\n` +
    `// ${news.length} notices · ${new Date().toISOString().slice(0, 10)}.\n` +
    `/* eslint-disable */\n` +
    `export const AYUSH_NEWS = ${JSON.stringify(news, null, 2)};\n` +
    `export const AYUSH_NEWS_AT = ${JSON.stringify(new Date().toISOString().slice(0, 10))};\n`;
  writeFileSync(OUT, out);
  console.log(`news: ${news.length} items → app/src/ayush/news.js`);
}

main().catch((e) => { console.error(e.message); process.exit(1); });